///
///	\file   ring.h
///
///	\brief  Class to specify ring parameters for Ring LWE
///         constructions. These are rings isomorphic to
///         Z_q[x] / (x^n + 1).
///         We require these rings to admit a negative
///         wrapped convolution in order to use the
///         fast NTT transform.
///

#include <ostream>
#include <vector>

//
// Constant ring parameters
//
// These parameters dictate the parameters of the RingLWE(n,q,sigma) assumption and
// have to satisfy the required security level (~128 bits). The assumed security
// level has to be verified by third party apps (e.g. lattice estimator) and
// published attacks.
//
struct RingParameters {
  RingPresetId ringID = RING_PRESET_NONE;
  Dim n = 0;

  // Low and high 64-bit constants for q and psi
  uint64_t qHi = 0ul;
  uint64_t qLo = 0ul;

  uint64_t psiHi = 0ul;
  uint64_t psiLo = 0ul;

  double sigma = 0.0;

  // The following flag dictates if the parameters
  // are suitable for the KP- or CP-ABE schemes.
  // If false, the parameters should only be used
  // for test purposes.
  bool production = false;
};

// Ring parameters (generated by ./src/tools/prime_moduli.cpp)
struct PresetRings {
  static constexpr std::array<RingParameters, 6> Parameters{{
      // q,  psi
      {RING_PRESET_TEST_0, 4, 0x0ul, 0x0000000000001E01ul, 0x0ul, 0x0000000000000785ul, 3.0,
       false}, // 7281, 1925
      {RING_PRESET_TEST_1, 8, 0x0ul, 0x000000000001FFE1ul, 0x0ul, 0x000000000000BEF2ul, 4.0,
       false}, // 131041, 48882
      {RING_PRESET_TEST_2, 64, 0x0ul, 0x0000000001FFFC81ul, 0x0ul, 0x000000000125DB90ul, 5.0,
       false}, // 33553537, 19258256
      {RING_PRESET_TEST_3, 256, 0x0ul, 0x000000003FFFF401ul, 0x0ul, 0x000000001CBB515Dul, 5.0,
       false}, // 1073738753, 482038109
      {RING_PRESET_PRODUCTION_57, 2048, 0x0ul, 0x01FFFFFFFFFFB001ul, 0x0ul, 0x011EF073E2282603ul,
       5.9, true}, // 144115188075835393, 80766223845434883
#ifdef __RCF64__
      {RING_PRESET_PRODUCTION_60, 2048, 0x0ul, 0x0FFFFFFFFFFFC001ul, 0x0ul, 0x006AE1D162874368ul,
       6.3, true}, // 1152921504606830593, 30084636948775784
#else
      {RING_PRESET_PRODUCTION_60, 4096, 0x3FFFFFFFFFFFFFFul, 0xFFFFFFFFFFFF0001ul,
       0x2902AF8DF13E2CCul, 0x32B073F6B599B60Bul, 3450000,
       true}, // 5316911983139663491615228241121312769, 3407018318025701634375629233177867787
#endif
  }};
};

/// \class	Ring
/// \brief	Generic container for ring-LWE groups

class Ring : public ObjectBase {
public:
  RingPresetId ringID;
  Rcf q;
  Dim n;
  Rcf nInv;
  Dim logq;
  Dim logn;
  Rcf psi = 0;
  Rcf psiInv = 0;

  // Vectors of size n with all powers
  // up to n-1 of psi and psi^{-1}
  // ** stored in bit-reversed order
  std::vector<Rcf> psiVecR;
  std::vector<Rcf> psiInvVecR;

  Ring(Rcf q, Dim n);
  Ring(Rcf q, Dim n, Rcf psi);
  Ring(RingParameters p);
  Ring(RingPresetId ringID);
  ~Ring;

  void setPsi(Rcf psi);

  friend std::ostream &operator<<(std::ostream &os, Ring &ring);
};

// Ring creation function
Ring *createNewRing(const std::string ringParams);

// Global function to get the appropriate sigma
double getSigmaFromRing(RingPresetId ringID);
